### ISSUE TITLE
Update to the latest version doesn't compile. The type 'IExecutableQuery' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by niemyjski** [approvals/ApprovalTests.Net#208]
For some reason when I upgrade to the latest version from 3.0.13 I get the following error:
```
C:\Code\Exceptionless\tests\Exceptionless.Api.Tests\Exceptionless.Api.Tests.csproj : warning NU1701: Package 'ApprovalTests 3.0.14' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
7>Utility\Approvals.cs(8,13,8,29): error CS0012: The type 'IExecutableQuery' is defined in an assembly that is not referenced. You must add a reference to assembly 'ApprovalUtilities, Version=3.0.0.0, Culture=neutral, PublicKeyToken=11bd7d124fc62e0f'.
```

I'm really not sure what's happening here but figured I'd log it as something broke in the latest version :)

**Comment by SimonCropp** [comment]
@niemyjski this is now fixed since netstandard is explicitly targeted
